name: GC3P
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _mutex_mxnet=0.0.40=mkl
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - botorch=0.2.1=0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h3eb4bd4_1
  - gpytorch=1.1.1=py_0
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py37_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libmklml=2019.0.5=0
  - libmxnet=1.5.0=mkl_hfe83b78_0
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2020.1=217
  - mkl-dnn=0.19=hfd86e86_1
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.3.0=py_0
  - mxnet=1.5.0=hea8a0af_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.3=py_0
  - pandas=1.0.3=py37h0573a6f_0
  - pcre=8.43=he6710b0_0
  - pip=20.0.2=py37_3
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py37_0
  - py=1.8.1=py_0
  - py-mxnet=1.5.0=py37hc738527_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pysocks=1.7.1=py37_0
  - pytest=5.4.2=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - scipy=1.4.1=py37h0b6359f_0
  - setuptools=47.1.1=py37_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - tk=8.6.8=hbc83047_0
  - tqdm=4.46.0=py_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - cycler==0.10.0
    - joblib==0.15.1
    - kiwisolver==1.2.0
    - matplotlib==3.2.1
    - scikit-learn==0.23.1
    - seaborn==0.10.1
    - sklearn==0.0
    - threadpoolctl==2.1.0
